// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Thunderstruck.DAL;

namespace Thunderstruck.DAL.Migrations
{
    [DbContext(typeof(ThunderstruckContext))]
    partial class ThunderstruckContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IconImageLink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Reward")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Achievement");
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.LocationData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<string>("LocationName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("LocationData");
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.UserAchievement", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.ToTable("UserAchievement");
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.UserLocationData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("LocationDataId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "LocationDataId");

                    b.HasIndex("LocationDataId");

                    b.ToTable("UsersLocationData");
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.AchievementHighVoltage", b =>
                {
                    b.HasBaseType("Thunderstruck.DOMAIN.Models.Achievement");

                    b.Property<bool>("IsThunderstorm")
                        .HasColumnType("bit");

                    b.ToTable("AchievementHighVoltage");
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.AchievementListening", b =>
                {
                    b.HasBaseType("Thunderstruck.DOMAIN.Models.Achievement");

                    b.Property<DateTime>("TotalPlayTime")
                        .HasColumnType("datetime2");

                    b.ToTable("AchievementListening");
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.AchievementRain", b =>
                {
                    b.HasBaseType("Thunderstruck.DOMAIN.Models.Achievement");

                    b.Property<bool>("IsRaining")
                        .HasColumnType("bit");

                    b.ToTable("AchievementRain");
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.AchievementSpeed", b =>
                {
                    b.HasBaseType("Thunderstruck.DOMAIN.Models.Achievement");

                    b.Property<double>("Speed")
                        .HasColumnType("float");

                    b.ToTable("AchievementSpeed");
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.UserAchievement", b =>
                {
                    b.HasOne("Thunderstruck.DOMAIN.Models.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thunderstruck.DOMAIN.Models.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.UserLocationData", b =>
                {
                    b.HasOne("Thunderstruck.DOMAIN.Models.LocationData", "LocationData")
                        .WithMany("UserLocationsData")
                        .HasForeignKey("LocationDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thunderstruck.DOMAIN.Models.User", "User")
                        .WithMany("UserLocationsData")
                        .HasForeignKey("LocationDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationData");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.AchievementHighVoltage", b =>
                {
                    b.HasOne("Thunderstruck.DOMAIN.Models.Achievement", null)
                        .WithOne()
                        .HasForeignKey("Thunderstruck.DOMAIN.Models.AchievementHighVoltage", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.AchievementListening", b =>
                {
                    b.HasOne("Thunderstruck.DOMAIN.Models.Achievement", null)
                        .WithOne()
                        .HasForeignKey("Thunderstruck.DOMAIN.Models.AchievementListening", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.AchievementRain", b =>
                {
                    b.HasOne("Thunderstruck.DOMAIN.Models.Achievement", null)
                        .WithOne()
                        .HasForeignKey("Thunderstruck.DOMAIN.Models.AchievementRain", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.AchievementSpeed", b =>
                {
                    b.HasOne("Thunderstruck.DOMAIN.Models.Achievement", null)
                        .WithOne()
                        .HasForeignKey("Thunderstruck.DOMAIN.Models.AchievementSpeed", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.LocationData", b =>
                {
                    b.Navigation("UserLocationsData");
                });

            modelBuilder.Entity("Thunderstruck.DOMAIN.Models.User", b =>
                {
                    b.Navigation("UserAchievements");

                    b.Navigation("UserLocationsData");
                });
#pragma warning restore 612, 618
        }
    }
}
